### ISSUE TITLE
The latest version may cause multiple mod conflicts,

### ISSUE THREAD

**Issue by li654300306** [pufmat/attributesmod#13]
The latest version may cause multiple mod conflicts. AI analysis shows that the latest version 0.6.4 leads to registration failures for multiple mods, while the latest version 1.19.2 and 0.6.4 lead to errors in NoGuiEvolution. Deleting NoGuiEvolution will prompt for Cataclysm and cyclic errors. I can 100% confirm the issue with the latest version of this mod. As long as you don't upgrade to the latest version, there won't be any errors. I hope you can handle it. Because English is not very good, it's machine translation, and the meaning may be incorrect. Please forgive me

**Comment by li654300306** [comment]
According to the crash log analysis, this is a crash during the game initialization phase. The main error messages are as follows:
The main issue is:
This is a property registration timing issue. The game attempted to register the swimming speed (forget: swimspeed) attribute at an incorrect time point.
The error occurred in the postLoadEvents method of Forge's GameData class, which is a critical stage of mod loading.

**Comment by neutralboolean** [comment]
I've also had crashes on game start with specifically this latest version (0.6.4). Rolling back to the previous version (0.6.2) allows start without issue. I am testing a moderately heavily modded game.
[crash-2024-11-23_03.18.15-client.txt](https://github.com/user-attachments/files/17879024/crash-2024-11-23_03.18.15-client.txt)

**Comment by pufmat** [comment]
Thanks for reporting fast. The problem should be fixed in version 0.6.5.

**Comment by EmoBubbleGum** [comment]
https://pastebin.com/97j9Fnqx

having compatibility issues too, with craft tweaker. deleting all my crafttweaker scripts doesnt fix it

edit: my bad, just needed to update puffish skills

**Comment by EmoBubbleGum** [comment]
[crash-2024-12-28_13.45.13-client.txt](https://github.com/user-attachments/files/18267316/crash-2024-12-28_13.45.13-client.txt)

oof, on older versions too. maybe i should make a different issue.
